CREATE TABLE IF NOT EXISTS EMPLOYEE (
    EMPLOYEEID TEXT,
    SALARY INTEGER
);
INSERT INTO EMPLOYEE (EMPLOYEEID, SALARY) VALUES
    ("5", 50000),
    ("9", 45000),
    ("2", 60000),
    ("4", 90000),
    ("12", 44000);
SELECT * FROM EMPLOYEE;
SELECT SUM(SALARY) AS TotalSalary FROM EMPLOYEE;
SELECT AVG(SALARY) AS AverageSalary FROM EMPLOYEE;
SELECT MAX(SALARY) AS MaxSalary FROM EMPLOYEE;
SELECT MIN(SALARY) AS MinSalary FROM EMPLOYEE;